import express from 'express'
import { body, validationResult } from 'express-validator'
import Task from '../models/Task.js'
import User from '../models/User.js'
import { authMiddleware, adminMiddleware } from '../middleware/auth.js'
import { useMockData } from '../config/database.js'
import { mockId, mockStore } from '../db/mockStore.js'
const router=express.Router();router.use(authMiddleware)
const canChange=(task,user)=>!task.assignmentLocked||user.role==='Admin'||String(task.assignedUserId)===String(user.userId)
router.get('/',async(req,res,next)=>{try{if(useMockData())return res.json({tasks:mockStore.tasks.filter(task=>!req.query.boardId||task.boardId===req.query.boardId)});res.json({tasks:await Task.find(req.query.boardId?{boardId:req.query.boardId}:{}).sort({columnId:1,order:1,createdAt:1})})}catch(error){next(error)}})
router.get('/:taskId',async(req,res,next)=>{try{const task=useMockData()?mockStore.tasks.find(item=>item.id===req.params.taskId):await Task.findById(req.params.taskId);if(!task)return res.status(404).json({error:'Task not found'});res.json({task})}catch(error){next(error)}})
router.post('/',[body('title').trim().notEmpty(),body('columnId').trim().notEmpty()],async(req,res,next)=>{try{const errors=validationResult(req);if(!errors.isEmpty())return res.status(400).json({errors:errors.array()});const input={...req.body};if(req.user.role!=='Admin'){delete input.assignedUserId;delete input.assignmentLocked}if(useMockData()){const task={...input,id:mockId(),createdBy:req.user.userId,createdAt:new Date()};mockStore.tasks.push(task);return res.status(201).json({task})}res.status(201).json({task:await Task.create({...input,createdBy:req.user.userId})})}catch(error){next(error)}})
router.put('/:taskId',async(req,res,next)=>{try{const allowed=['title','description','boardId','columnId','assignee','priority','type','dueDate','estimate','order'];if(req.user.role==='Admin')allowed.push('assignedUserId','assignmentLocked');const updates=Object.fromEntries(Object.entries(req.body).filter(([key])=>allowed.includes(key)));if(useMockData()){const task=mockStore.tasks.find(item=>item.id===req.params.taskId);if(!task)return res.status(404).json({error:'Task not found'});if(!canChange(task,req.user))return res.status(403).json({error:'This task is locked to its assigned member'});Object.assign(task,updates,{updatedAt:new Date()});return res.json({task})}const task=await Task.findById(req.params.taskId);if(!task)return res.status(404).json({error:'Task not found'});if(!canChange(task,req.user))return res.status(403).json({error:'This task is locked to its assigned member'});Object.assign(task,updates);await task.save();res.json({task})}catch(error){next(error)}})
router.patch('/:taskId/assignment',adminMiddleware,[body('assignmentLocked').isBoolean()],async(req,res,next)=>{try{const user=req.body.assignedUserId?(useMockData()?mockStore.users.find(item=>item.id===req.body.assignedUserId):await User.findById(req.body.assignedUserId)):null;if(req.body.assignedUserId&&!user)return res.status(404).json({error:'Assigned user not found'});const updates={assignedUserId:req.body.assignedUserId||null,assignmentLocked:Boolean(req.body.assignmentLocked&&req.body.assignedUserId),assignee:user?.username||''};if(useMockData()){const task=mockStore.tasks.find(item=>item.id===req.params.taskId);if(!task)return res.status(404).json({error:'Task not found'});Object.assign(task,updates,{updatedAt:new Date()});return res.json({task})}const task=await Task.findByIdAndUpdate(req.params.taskId,updates,{new:true});if(!task)return res.status(404).json({error:'Task not found'});res.json({task})}catch(error){next(error)}})
router.delete('/:taskId',async(req,res,next)=>{try{if(useMockData()){const index=mockStore.tasks.findIndex(item=>item.id===req.params.taskId);if(index<0)return res.status(404).json({error:'Task not found'});if(!canChange(mockStore.tasks[index],req.user))return res.status(403).json({error:'This task is locked to its assigned member'});const[task]=mockStore.tasks.splice(index,1);return res.json({message:'Task deleted successfully',task})}const task=await Task.findById(req.params.taskId);if(!task)return res.status(404).json({error:'Task not found'});if(!canChange(task,req.user))return res.status(403).json({error:'This task is locked to its assigned member'});await task.deleteOne();res.json({message:'Task deleted successfully',task})}catch(error){next(error)}})
export default router
