import React,{useEffect,useState}from'react'
import{useAuth}from'../context/AuthContext'
import{useBoard}from'../context/BoardContext'
import apiClient from'../api/client'
import styles from'./AdminPanel.module.css'
import'./AdminPanelStable.css'
const EMPTY={username:'',email:'',password:'',role:'Standard User'}
export default function AdminPanel(){
 const{user}=useAuth(),{board,handleSetAssignment}=useBoard();const[users,setUsers]=useState([]),[form,setForm]=useState(EMPTY),[editing,setEditing]=useState(null),[assignments,setAssignments]=useState({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');const tasks=board?.columns?.flatMap(c=>c.tasks||[])||[]
 useEffect(()=>{apiClient.getAllUsers().then(r=>setUsers(r.users||[])).catch(e=>setError(e.error||e.message||'Could not load users')).finally(()=>setLoading(false))},[])
 const save=async e=>{e.preventDefault();setBusy('user');setError('');try{const p={...form,password:form.password||undefined},r=editing?await apiClient.updateUser(editing,p):await apiClient.createUser(p);setUsers(c=>editing?c.map(x=>x.id===editing?r.user:x):[r.user,...c]);setForm(EMPTY);setEditing(null)}catch(e){setError(e.error||e.errors?.[0]?.msg||e.message)}finally{setBusy('')}}
 const changeRole=async u=>{setBusy(u.id);try{const r=await apiClient.updateUserRole(u.id,u.role==='Admin'?'Standard User':'Admin');setUsers(c=>c.map(x=>x.id===u.id?r.user:x))}catch(e){setError(e.error||e.message)}finally{setBusy('')}}
 const remove=async u=>{if(!window.confirm(`Delete ${u.username}? Their locked tasks will be unlocked.`))return;setBusy(u.id);try{await apiClient.deleteUser(u.id);setUsers(c=>c.filter(x=>x.id!==u.id))}catch(e){setError(e.error||e.message)}finally{setBusy('')}}
 const assign=async t=>{const id=assignments[t.id]??t.assignedUserId??'';setBusy(t.id);try{await handleSetAssignment(t.id,id,Boolean(id))}catch(e){setError(e.error||e.message)}finally{setBusy('')}}
 return <div className={styles.page}><header><div><span>ADMINISTRATION</span><h1>Control center</h1><p>Manage people, permissions, and protected work assignments.</p></div><div className={styles.adminBadge}>◆ Administrator</div></header>
 <section className={styles.stats}><article><span>Total users</span><strong>{users.length}</strong><small>Workspace accounts</small></article><article><span>Administrators</span><strong>{users.filter(x=>x.role==='Admin').length}</strong><small>Privileged accounts</small></article><article><span>Project tasks</span><strong>{tasks.length}</strong><small>Across the board</small></article><article><span>Locked tasks</span><strong>{tasks.filter(x=>x.assignmentLocked).length}</strong><small>Protected assignments</small></article></section>{error&&<div className={styles.error}>{error}</div>}
 <section className={styles.users}><div className={styles.sectionHead}><div><span>USER CRUD</span><h2>{editing?'Edit account':'Create account'}</h2></div>{editing&&<button onClick={()=>{setEditing(null);setForm(EMPTY)}}>Cancel edit</button>}</div><form className="adminUserForm" onSubmit={save}><input required placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required={!editing} type="password" minLength="6" placeholder={editing?'New password (optional)':'Temporary password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>Standard User</option><option>Admin</option></select><button disabled={busy==='user'}>{busy==='user'?'Saving…':editing?'Save changes':'Add user'}</button></form>
 {loading?<div className="adminEmpty">Loading accounts…</div>:users.length===0?<div className="adminEmpty">No accounts returned.</div>:<>{users.map(u=><div className={styles.userRow} key={u.id}><div className={styles.person}><i>{u.username.slice(0,2).toUpperCase()}</i><span><strong>{u.username}</strong><small>{u.email}</small></span></div><span className={u.role==='Admin'?styles.roleAdmin:styles.roleUser}>{u.role}</span><button disabled={u.id===user?.id||busy===u.id} onClick={()=>changeRole(u)}>{u.role==='Admin'?'Demote':'Promote'}</button><div className="adminRowActions"><button onClick={()=>{setEditing(u.id);setForm({username:u.username,email:u.email,password:'',role:u.role})}}>Edit</button><button className="adminDanger" disabled={u.id===user?.id} onClick={()=>remove(u)}>Delete</button></div></div>)}</>}</section>
 <section className={styles.users}><div className={styles.sectionHead}><div><span>PROTECTED ASSIGNMENTS</span><h2>Assign and lock tasks</h2></div></div><div className="adminAssignments">{tasks.length===0?<div className="adminEmpty">No tasks available. Create tasks on the board first.</div>:tasks.map(t=><div className="adminAssignment" key={t.id}><div><strong>{t.title}</strong><small>{t.assignmentLocked?`🔒 Locked to ${t.assignee}`:'Unlocked — any member can work on it'}</small></div><select value={assignments[t.id]??t.assignedUserId??''} onChange={e=>setAssignments({...assignments,[t.id]:e.target.value})}><option value="">No locked member</option>{users.filter(u=>u.role!=='Admin').map(u=><option value={u.id} key={u.id}>{u.username}</option>)}</select><button disabled={busy===t.id} onClick={()=>assign(t)}>{busy===t.id?'Saving…':(assignments[t.id]??t.assignedUserId)?'Assign & lock':'Unlock task'}</button></div>)}</div></section></div>
}
