import React, { useMemo, useState } from 'react'; import { useBoard } from '../context/BoardContext'; import styles from './Reports.module.css'
const doneCol=t=>/done|complete|deployed|production/i.test(t),doingCol=t=>/doing|progress|development/i.test(t)
function Bars({data}){const max=Math.max(1,...data.map(x=>x.value));return <div className={styles.bars}>{data.map(x=><div key={x.label}><span>{x.value}</span><i style={{height:`${Math.max(8,x.value/max*100)}%`}}/><small>{x.label}</small></div>)}</div>}
export default function Reports(){const {board,activities}=useBoard();const [range,setRange]=useState('7 days'),[replay,setReplay]=useState(0);const tasks=board.columns.flatMap(c=>c.tasks.map(t=>({...t,status:c.title}))),done=tasks.filter(t=>doneCol(t.status)),active=tasks.filter(t=>doingCol(t.status)),today=new Date(new Date().toDateString()),overdue=tasks.filter(t=>t.dueDate&&!doneCol(t.status)&&new Date(t.dueDate)<today),blocked=tasks.filter(t=>t.relationship==='depends-on'),total=tasks.length,completion=total?Math.round(done.length/total*100):0
 const workload=useMemo(()=>Object.entries(tasks.reduce((map,t)=>(map[t.assignee||'Unassigned']=(map[t.assignee||'Unassigned']||0)+1,map),{})).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value),[tasks]);const types=['Feature','Bug','UI'].map(label=>({label,value:tasks.filter(t=>t.type===label).length}));const healthPenalty=overdue.length*10+blocked.length*6+(workload[0]?.value||0);const health=Math.max(0,Math.min(100,Math.round(65+completion*.35-healthPenalty)));const pulse=health>=80?'Strong':health>=60?'Stable':'At risk'
 const achievements=[completion===100&&'Perfect sprint',done.length>=5&&'Momentum maker',overdue.length===0&&total>0&&'Zero overdue',workload.length>1&&Math.max(...workload.map(x=>x.value))-Math.min(...workload.map(x=>x.value))<=1&&'Balanced crew'].filter(Boolean)
 const exportCsv=()=>{const rows=[['Title','Status','Assignee','Priority','Due date'],...tasks.map(t=>[t.title,t.status,t.assignee,t.priority,t.dueDate])];const blob=new Blob([rows.map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='novasync-report.csv';a.click();URL.revokeObjectURL(url)}
 return <div className={styles.container}><header className={styles.header}><div><span>WORKSPACE INTELLIGENCE</span><h1>Reports & insights</h1><p>Live signals from your current sprint.</p></div><div><select value={range} onChange={e=>setRange(e.target.value)}><option>7 days</option><option>30 days</option><option>This sprint</option></select><button onClick={exportCsv}>⇩ Export CSV</button></div></header>
 <section className={styles.pulse}><div className={styles.score} style={{'--score':health}}><div><strong>{health}</strong><small>health score</small></div></div><div><span>PROJECT PULSE · {pulse.toUpperCase()}</span><h2>{overdue.length?`${overdue.length} overdue task${overdue.length>1?'s':''} need attention.`:'Your sprint is moving in the right direction.'}</h2><p>{blocked.length?`${blocked.length} dependent task${blocked.length>1?'s are':' is'} waiting on other work. `:''}{completion}% of the board is complete with {active.length} currently active.</p></div><div className={styles.pulseFacts}><span><b>{overdue.length}</b> overdue</span><span><b>{blocked.length}</b> blocked</span><span><b>{completion}%</b> complete</span></div></section>
 <section className={styles.metrics}>{[[total,'Total tasks','Across the board'],[active.length,'In motion','Active right now'],[done.length,'Completed','Delivered this sprint'],[overdue.length,'At risk','Past their due date']].map(([v,l,n])=><article key={l}><span>{l}</span><strong>{String(v).padStart(2,'0')}</strong><small>{n}</small></article>)}</section>
 <section className={styles.grid}><article className={styles.card}><div className={styles.cardHead}><div><span>CAPACITY</span><h3>Team workload</h3></div><small>{range}</small></div><Bars data={workload.slice(0,7)}/></article><article className={styles.card}><div className={styles.cardHead}><div><span>WORK MIX</span><h3>Tasks by type</h3></div></div><div className={styles.donut} style={{background:`conic-gradient(#86a5cb 0 ${total?types[0].value/total*100:0}%,#b38c73 0 ${total?(types[0].value+types[1].value)/total*100:0}%,#9182ad 0)`}}><i/></div><div className={styles.legend}>{types.map(x=><span key={x.label}>{x.label}<b>{x.value}</b></span>)}</div></article></section>
 <section className={styles.grid}><article className={styles.card}><div className={styles.cardHead}><div><span>SMART STAND-UP</span><h3>Today’s briefing</h3></div></div><div className={styles.brief}><p><b>Completed</b>{done.length?`${done.length} task${done.length>1?'s':''} delivered.`:'No completions logged yet.'}</p><p><b>In progress</b>{active.length?active.slice(0,2).map(t=>t.title).join(' · '):'Ready for the next task.'}</p><p><b>Blockers</b>{blocked.length?blocked.map(t=>t.title).slice(0,2).join(' · '):'No blockers detected.'}</p></div></article><article className={styles.card}><div className={styles.cardHead}><div><span>MILESTONES</span><h3>Team achievements</h3></div></div><div className={styles.achievements}>{achievements.length?achievements.map((x,i)=><div key={x}><i>{['✦','◆','◎','◈'][i]}</i><span><b>{x}</b><small>Unlocked by this sprint</small></span></div>):<p>Complete more work to unlock the first milestone.</p>}</div></article></section>
 <section className={`${styles.card} ${styles.timeline}`}><div className={styles.cardHead}><div><span>TIME MACHINE</span><h3>Activity replay</h3></div><b>{activities.length?`${replay+1} / ${activities.length}`:'No events yet'}</b></div>{activities.length?<><input type="range" min="0" max={activities.length-1} value={replay} onChange={e=>setReplay(Number(e.target.value))}/><div className={styles.event}><i>◷</i><span><b>{activities.slice().reverse()[replay]?.text}</b><small>{new Date(activities.slice().reverse()[replay]?.timestamp).toLocaleString()}</small></span></div></>:<p>Board changes made during this session will appear here.</p>}</section>
 </div>}
