import React, { useEffect, useRef, useState } from 'react'; import { useAuth } from '../context/AuthContext'; import styles from './UserSettings.module.css'
const initials=name=>(name||'NS').split(/[ _-]/).map(x=>x[0]).join('').slice(0,2).toUpperCase()
export default function UserSettings(){const {user,updateProfile}=useAuth(),fileRef=useRef(null);const [form,setForm]=useState({username:'',email:'',bio:'',timezone:'Asia/Colombo',avatar:'',emailNotifications:true,compactMode:false,currentPassword:'',newPassword:'',confirmPassword:''}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 useEffect(()=>setForm(current=>({...current,username:user?.username||'',email:user?.email||'',bio:user?.bio||'',timezone:user?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Colombo',avatar:user?.avatar||'',emailNotifications:user?.preferences?.emailNotifications!==false,compactMode:Boolean(user?.preferences?.compactMode),theme:user?.preferences?.theme||localStorage.getItem('novasync-theme')||'dark'})),[user])
 const update=(key,value)=>{setForm(current=>({...current,[key]:value}));if(key==='theme'){document.documentElement.dataset.theme=value;localStorage.setItem('novasync-theme',value)}setError('');setMessage('')}
 const photo=event=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return setError('Choose a JPG, PNG, WebP, or GIF image.');if(file.size>1024*1024)return setError('Profile photo must be smaller than 1 MB.');const reader=new FileReader();reader.onload=()=>update('avatar',reader.result);reader.readAsDataURL(file)}
 const submit=async event=>{event.preventDefault();if(!form.username.trim()||!form.email.trim())return setError('Name and email are required.');if(form.newPassword&&form.newPassword!==form.confirmPassword)return setError('New passwords do not match.');setBusy(true);setError('');setMessage('');try{await updateProfile({username:form.username.trim(),email:form.email.trim(),bio:form.bio.trim(),timezone:form.timezone,avatar:form.avatar,preferences:{emailNotifications:form.emailNotifications,compactMode:form.compactMode,theme:form.theme},currentPassword:form.currentPassword,newPassword:form.newPassword});setMessage('Your profile has been updated.');setForm(current=>({...current,currentPassword:'',newPassword:'',confirmPassword:''}))}catch(err){setError(err.error||err.errors?.[0]?.msg||err.message||'Could not update your profile.')}finally{setBusy(false)}}
 return <main className={styles.page}><header><span>PERSONAL WORKSPACE</span><h1>Settings</h1><p>Manage your public profile, account security, and everyday preferences.</p></header><form onSubmit={submit} className={styles.layout}>
  <aside className={styles.profileCard}><div className={styles.avatar}>{form.avatar?<img src={form.avatar} alt="Profile preview"/>:<span>{initials(form.username)}</span>}<button type="button" onClick={()=>fileRef.current?.click()}>Edit</button></div><h2>{form.username||'Your profile'}</h2><p>{user?.role||'Standard User'}</p><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={photo}/><button type="button" className={styles.upload} onClick={()=>fileRef.current?.click()}>Upload new photo</button>{form.avatar&&<button type="button" className={styles.remove} onClick={()=>update('avatar','')}>Remove photo</button>}<small>JPG, PNG, WebP or GIF · maximum 1 MB</small><div className={styles.profileMeta}><span>Account type <b>{user?.role||'Member'}</b></span><span>Member since <b>{user?.createdAt?new Date(user.createdAt).toLocaleDateString(): 'NovaSync member'}</b></span></div></aside>
  <div className={styles.sections}>{error&&<div className={styles.error}>! {error}</div>}{message&&<div className={styles.success}>✓ {message}</div>}
   <section><div className={styles.sectionTitle}><span>01</span><div><h2>Profile information</h2><p>This information is visible to your teammates.</p></div></div><div className={styles.two}><label>Display name<input value={form.username} onChange={e=>update('username',e.target.value)} maxLength="40"/></label><label>Email address<input type="email" value={form.email} onChange={e=>update('email',e.target.value)}/></label></div><label>Short bio<textarea rows="3" maxLength="160" value={form.bio} onChange={e=>update('bio',e.target.value)} placeholder="Tell your team what you work on…"/><small>{form.bio.length}/160</small></label><label>Time zone<select value={form.timezone} onChange={e=>update('timezone',e.target.value)}><option>Asia/Colombo</option><option>Asia/Kolkata</option><option>Europe/London</option><option>America/New_York</option><option>America/Los_Angeles</option><option>Australia/Sydney</option><option>UTC</option></select></label></section>
   <section><div className={styles.sectionTitle}><span>02</span><div><h2>Preferences</h2><p>Choose how NovaSync looks and behaves for you.</p></div></div><div className={styles.themePicker} aria-label="Theme"><button type="button" aria-label="Use light theme" aria-pressed={form.theme==='light'} className={form.theme==='light'?styles.themeActive:''} onClick={()=>update('theme','light')}><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.66 6.34l1.41-1.41"/></svg><span>Light</span></button><button type="button" aria-label="Use dark theme" aria-pressed={form.theme==='dark'} className={form.theme==='dark'?styles.themeActive:''} onClick={()=>update('theme','dark')}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8z"/></svg><span>Dark</span></button></div><label className={styles.toggle}><span><b>Email notifications</b><small>Receive important task and message updates.</small></span><input type="checkbox" checked={form.emailNotifications} onChange={e=>update('emailNotifications',e.target.checked)}/><i/></label><label className={styles.toggle}><span><b>Compact board cards</b><small>Show more tasks with reduced spacing.</small></span><input type="checkbox" checked={form.compactMode} onChange={e=>update('compactMode',e.target.checked)}/><i/></label></section>
   <section><div className={styles.sectionTitle}><span>03</span><div><h2>Password & security</h2><p>Leave these fields empty to keep your current password.</p></div></div><label>Current password<input type="password" autoComplete="current-password" value={form.currentPassword} onChange={e=>update('currentPassword',e.target.value)} placeholder="Required to change password"/></label><div className={styles.two}><label>New password<input type="password" autoComplete="new-password" minLength="6" value={form.newPassword} onChange={e=>update('newPassword',e.target.value)} placeholder="At least 6 characters"/></label><label>Confirm password<input type="password" autoComplete="new-password" value={form.confirmPassword} onChange={e=>update('confirmPassword',e.target.value)} placeholder="Repeat new password"/></label></div></section>
   <div className={styles.actions}><span>Changes apply to your account only.</span><button disabled={busy}>{busy?'Saving changes…':'Save profile changes'}</button></div>
  </div></form></main>}
