import { pageItems } from './adminPagination'
import React, { useEffect, useRef, useState } from 'react'
import { useAuth } from '../context/AuthContext'
import { useBoard } from '../context/BoardContext'
import apiClient from '../api/client'
import AdminTeamMessages from '../components/AdminTeamMessages'
import { Pagination } from '../components/AdminPagination'
import Modal from '../components/Modal'
import ConfirmDialog from '../components/ConfirmDialog'
import { adminStress } from '../fixtures/adminStress'
import styles from './AdminPanel.module.css'
const EMPTY = { username: '', email: '', password: '', role: 'Standard User' }
const errorText = error => error.error || error.errors?.[0]?.msg || error.message || 'Could not complete this request.'
export default function AdminPanel() {
  const { user } = useAuth(), { board, handleSetAssignment } = useBoard()
  const preview = import.meta.env.DEV && new URLSearchParams(window.location.search).get('adminPreview') === 'stress'
  const [tab, setTab] = useState(() => preview ? new URLSearchParams(window.location.search).get('tab') || 'accounts' : 'accounts')
  const [users, setUsers] = useState(preview ? adminStress.users : [])
  const [form, setForm] = useState(EMPTY), [editing, setEditing] = useState(null), [modal, setModal] = useState(false), [removing, setRemoving] = useState(null)
  const [assignments, setAssignments] = useState({}), [loading, setLoading] = useState(!preview), [busy, setBusy] = useState(''), [error, setError] = useState(''), [formError, setFormError] = useState(''), [notice, setNotice] = useState('')
  const [query, setQuery] = useState(''), [role, setRole] = useState('All'), [page, setPage] = useState(0)
  const pending = useRef(false)
  const tasks = preview ? adminStress.tasks : board?.columns?.flatMap(column => column.tasks || []) || []
  useEffect(() => { if (preview) return; let alive = true; apiClient.getAllUsers().then(result => { if (alive) setUsers(result.users || []) }).catch(err => { if (alive) setError(errorText(err)) }).finally(() => { if (alive) setLoading(false) }); return () => { alive = false } }, [preview])
  const openForm = account => { setEditing(account?.id || null); setForm(account ? { username: account.username, email: account.email, role: account.role, password: '' } : EMPTY); setFormError(''); setModal(true) }
  const save = async event => {
    event.preventDefault(); if (pending.current || preview) return
    pending.current = true; setBusy('user'); setFormError('')
    try { const payload = { ...form, username: form.username.trim(), email: form.email.trim(), password: form.password || undefined }; const result = editing ? await apiClient.updateUser(editing, payload) : await apiClient.createUser(payload); setUsers(current => editing ? current.map(account => account.id === editing ? result.user : account) : [result.user, ...current]); setModal(false); setNotice(editing ? 'Account updated.' : 'Account created.'); setForm(EMPTY) }
    catch (err) { setFormError(errorText(err)) } finally { pending.current = false; setBusy('') }
  }
  const remove = async () => { if (preview) return; await apiClient.deleteUser(removing.id); setUsers(current => current.filter(account => account.id !== removing.id)); setRemoving(null); setNotice('Account deleted.'); }
  const assign = async task => {
    if (pending.current || preview) return
    pending.current = true; setBusy(task.id); setError('')
    try { const id = assignments[task.id] ?? task.assignedUserId ?? ''; await handleSetAssignment(task.id, id, Boolean(id)); setNotice(id ? 'Assignment locked. The board and timelines now show the protected assignment.' : 'Assignment unlocked.'); setAssignments(current => { const next = { ...current }; delete next[task.id]; return next }) }
    catch (err) { setError(errorText(err)) } finally { pending.current = false; setBusy('') }
  }
  const matches = value => value.toLowerCase().includes(query.trim().toLowerCase())
  const accounts = users.filter(account => (role === 'All' || (role === 'System' ? account.accountType === 'system' : account.role === role && account.accountType !== 'system')) && matches(`${account.username} ${account.email} ${(account.permissions || []).join(' ')}`))
  const filteredTasks = tasks.filter(task => matches(`${task.title} ${task.assignee || ''}`))
  const result = pageItems(tab === 'tasks' ? filteredTasks : accounts, page)
  const changeTab = value => { setTab(value); setQuery(''); setPage(0); setRole('All') }
  return <div className={styles.adminView}><div className={styles.content}>
    <header className={styles.header}><div><span className={styles.eyebrow}>ADMINISTRATION</span><h1>Control center</h1><p>People, protected assignments and workspace audit history.</p></div><span className={styles.adminBadge}>◆ Administrator</span></header>
    {preview && <p className={styles.notice}>Stress preview · sample accounts and 5,000 audit entries. Administrative actions are disabled.</p>}
    <section className={styles.stats}>{[[users.length, 'Accounts'], [users.filter(account => account.role === 'Admin').length, 'Administrators'], [tasks.length, 'Project tasks'], [tasks.filter(task => task.assignmentLocked).length, 'Locked assignments']].map(([value, label]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</section>
    <div className={styles.tabs} role="tablist" aria-label="Administration sections">{[['accounts', 'User accounts'], ['audit', 'Message audits'], ['tasks', 'Task security']].map(([value, label], index, tabs) => <button key={value} role="tab" id={`admin-tab-${value}`} aria-selected={tab === value} aria-controls={`admin-panel-${value}`} tabIndex={tab === value ? 0 : -1} onClick={() => changeTab(value)} onKeyDown={event => { const next = event.key === 'ArrowRight' ? (index + 1) % tabs.length : event.key === 'ArrowLeft' ? (index + tabs.length - 1) % tabs.length : event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : null; if (next !== null) { event.preventDefault(); changeTab(tabs[next][0]); document.getElementById(`admin-tab-${tabs[next][0]}`)?.focus() } }}>{label}</button>)}</div>
    {error && <p className={styles.error} role="alert">{error}</p>}{notice && <p className={styles.notice} role="status">{notice}</p>}
    <div role="tabpanel" id={`admin-panel-${tab}`} aria-labelledby={`admin-tab-${tab}`}>
      {tab === 'audit' ? <AdminTeamMessages previewMessages={preview ? adminStress.messages : undefined}/> : <section className={styles.panel}>
        <header className={styles.sectionHead}><div><span className={styles.eyebrow}>{tab === 'accounts' ? 'IDENTITY & ACCESS' : 'PROTECTED ASSIGNMENTS'}</span><h2>{tab === 'accounts' ? 'User accounts' : 'Assign and lock tasks'}</h2><p>{tab === 'accounts' ? 'Review account details and edit workspace roles.' : 'A locked task can be edited by its assigned member or an administrator.'}</p></div>{tab === 'accounts' && <button disabled={preview || Boolean(busy)} className={styles.primary} onClick={() => openForm()}>＋ Create account</button>}</header>
        <div className={styles.filters}><label>Search {tab === 'accounts' ? 'accounts' : 'tasks'}<input type="search" value={query} placeholder={tab === 'accounts' ? 'Name, email or permission…' : 'Task title or assignee…'} onChange={event => { setQuery(event.target.value); setPage(0) }}/></label>{tab === 'accounts' && <label>Account role<select value={role} onChange={event => { setRole(event.target.value); setPage(0) }}><option value="All">All roles</option><option>Admin</option><option>Standard User</option>{users.some(account => account.accountType === 'system') && <option value="System">System integration</option>}</select></label>}</div>
        <div className={styles.tableScroll} tabIndex={0} aria-label={tab === 'accounts' ? 'Account table' : 'Task security table'}><table><thead><tr>{(tab === 'accounts' ? ['Account', 'Role & permissions', 'Actions'] : ['Task', 'Assignment status', 'Assign member', 'Action']).map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>
          {loading ? <tr><td colSpan={tab === 'accounts' ? 3 : 4}>Loading accounts…</td></tr> : !result.rows.length ? <tr><td colSpan={tab === 'accounts' ? 3 : 4}>No matching {tab === 'accounts' ? 'accounts' : 'tasks'}.</td></tr> : tab === 'accounts' ? result.rows.map(account => <tr key={account.id}><td><div className={styles.person}><i aria-hidden="true">{account.accountType === 'system' ? '⚙' : account.username.slice(0, 2).toUpperCase()}</i><div><strong>{account.username}{account.id === user?.id && ' (you)'}</strong><small>{account.email}</small></div></div></td><td><span className={`${styles.badge} ${account.accountType === 'system' ? styles.system : account.role === 'Admin' ? styles.admin : styles.human}`}>{account.accountType === 'system' ? '⚙ System integration' : account.role === 'Admin' ? '◆ Admin' : '● Human · Member'}</span>{account.permissions?.length > 0 && <details><summary>Permission scopes ({account.permissions.length})</summary><ul>{account.permissions.map(permission => <li key={permission}>{permission}</li>)}</ul></details>}</td><td><div className={styles.actions}><button disabled={preview || Boolean(busy) || account.accountType === 'system'} onClick={() => openForm(account)}>Edit</button><button className={styles.danger} disabled={preview || Boolean(busy) || account.id === user?.id || account.accountType === 'system'} onClick={() => setRemoving(account)}>Delete</button></div></td></tr>) : result.rows.map(task => <tr key={task.id}><td><strong>{task.title}</strong></td><td><span className={`${styles.badge} ${task.assignmentLocked ? styles.locked : styles.human}`}>{task.assignmentLocked ? '🔒 Locked' : 'Unlocked'}</span><small>{task.assignee || 'No assigned member'}</small></td><td><select aria-label={`Assign member to ${task.title}`} disabled={preview || Boolean(busy)} value={assignments[task.id] ?? task.assignedUserId ?? ''} onChange={event => setAssignments({ ...assignments, [task.id]: event.target.value })}><option value="">No locked member</option>{task.assignedUserId && !users.some(account => account.id === task.assignedUserId) && <option value={task.assignedUserId}>{task.assignee || 'Unavailable member'}</option>}{users.filter(account => account.accountType !== 'system').map(account => <option value={account.id} key={account.id}>{account.username}</option>)}</select></td><td><button disabled={preview || Boolean(busy)} onClick={() => assign(task)}>{busy === task.id ? 'Saving…' : (assignments[task.id] ?? task.assignedUserId) ? 'Assign & lock' : 'Unlock task'}</button></td></tr>)}
        </tbody></table></div><Pagination count={tab === 'accounts' ? accounts.length : filteredTasks.length} page={result.current} pages={result.pages} onChange={setPage}/>
        {tab === 'accounts' && <p className={styles.caption}>Human accounts use workspace roles. Hardware credential management is not connected.</p>}
      </section>}
    </div>
    <Modal isOpen={modal} title={editing ? 'Edit account' : 'Create account'} onClose={() => { if (!pending.current) setModal(false) }} compact solid><form className={styles.accountForm} onSubmit={save}><p>{editing ? 'Update account details and workspace access.' : 'Create an account with a temporary password. No invitation email is sent.'}</p><fieldset disabled={Boolean(busy)}><label>Username<input autoFocus required minLength={2} maxLength={50} value={form.username} onChange={event => setForm({ ...form, username: event.target.value })}/></label><label>Email<input required type="email" maxLength={254} value={form.email} onChange={event => setForm({ ...form, email: event.target.value })}/></label><label>{editing ? 'New password (optional)' : 'Temporary password'}<input required={!editing} type="password" minLength={6} autoComplete="new-password" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })}/></label><label>Role<select disabled={editing === user?.id} value={form.role} onChange={event => setForm({ ...form, role: event.target.value })}><option>Standard User</option><option>Admin</option></select></label></fieldset>{formError && <p className={styles.error} role="alert">{formError}</p>}<footer><button type="button" disabled={Boolean(busy)} onClick={() => setModal(false)}>Cancel</button><button disabled={Boolean(busy)}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Create account'}</button></footer></form></Modal>
    <ConfirmDialog isOpen={Boolean(removing)} title="Delete account" message="The account will be deleted and its locked assignments released." taskName={removing?.username} itemLabel="account" isDangerous confirmText="Delete account" onCancel={() => setRemoving(null)} onConfirm={remove}/>
  </div></div>
}
